### ISSUE TITLE
Upgrade eslint (eslint-scope issue)

### ISSUE THREAD

**Issue by coreylight** [iopipe/iopipe-scripts#11]
There is a virus/compromise in eslint-scope at version 3.7.1

https://github.com/eslint/eslint-scope/issues/39

**Comment by pselle** [comment]
The issue isn't an upgrade, it's pinning to a _downgrade_ and we appear to be ok -- friend pointed out:

> I just learned that `es-lint` version 3.7.2 + is compromised

when I ran `yarn list eslint-scope` I got 3.7.1 so we're good as I can see

**Comment by pselle** [comment]
> Pin the version of eslint-scope to 3.7.1, one way is to add the resolutions to your package.json
from the original report. If we trust `yarn.lock` we _are_ currently pinned
